dashboard/urls.py
from django.urls import path

# from django.contrib.auth import views as auth_views
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="home"),
    path("edit/", views.edit, name="edit"),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("dashboard.urls")),
    # path("accounts2/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("dashboard/", include("dashboard.urls")),
    # path("accounts2/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from accounts.forms import UserEditForm
from django.contrib import messages

# Create your views here.


@login_required
def dashboard(request):
    return render(request, "dashboard/home.html", {"section": "dashboard"})


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "Profile updated " "successfully")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=request.user)
    return render(request, "dashboard/edit.html", {"user_form": user_form})

dashboard/templates/dashboard/edit.html
{% extends "base.html" %}

{% block title %}
    Edit your account
{% endblock title %}

{% block content %}
    <h1>
        Edit your account
    </h1>
    <p>
        You can edit your account using the following form:
    </p>
    <form method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p>
            <input type="submit" value="Save changes">
        </p>
    </form>
{% endblock content %}

dashboard/templates/dashboard/home.html
{% extends "base.html" %}

{% block title %}
    Dashboard
{% endblock title %}

{% block content %}
    <h1>
        Dashboard
    </h1>
    <p>
        Welcome to your dashboard. You can <a href="{% url "dashboard:edit" %}">edit your profile</a> or <a href="{% url "account_change_password" %}">change your password</a>.
    </p>
{% endblock content %}